import fs from "node:fs/promises";
import path from "node:path";
import type {
  AnalysisFinding,
  AnalysisSeverity,
  ProofVerdict
} from "../analysis/model.js";
import { finalizeFinding } from "../analysis/evidence.js";
import { runBoundedProcess } from "../analysis/processRunner.js";
import type { SynthesizedInvariant } from "./invariantSynthesis.js";
import {
  checkProofSanity,
  type ProofSanityReport
} from "./proofSanity.js";

export type FormalTool =
  | "HALMOS"
  | "CERTORA"
  | "KONTROL";

export type FormalPropertyArtifact = {
  invariantId: string;
  tool: FormalTool;
  fileName: string;
  content: string;
  requiresBinding: boolean;
};

export type FormalVerificationJob = {
  id: string;
  tool: FormalTool;
  projectPath: string;
  propertyPath: string;
  configPath?: string;
  allowRemote?: boolean;
  timeoutMs?: number;
};

export type FormalVerificationResult = {
  jobId: string;
  tool: FormalTool;
  state:
    | "PROVED_UNDER_SPEC"
    | "DISPROVED"
    | "INCONCLUSIVE"
    | "UNAVAILABLE";
  proofVerdict: ProofVerdict;
  sanity: ProofSanityReport;
  stdout: string;
  stderr: string;
  finding?: AnalysisFinding;
  limitations: string[];
};

function safeIdentifier(value: string) {
  const cleaned = value
    .replace(/[^A-Za-z0-9_]/g, "_")
    .slice(0, 80);
  return /^[0-9]/.test(cleaned)
    ? "_" + cleaned
    : cleaned;
}

function assumptionComments(
  invariant: SynthesizedInvariant
) {
  return invariant.assumptions.map(
    value => "// assumption: " + value
  );
}

export function generateFormalArtifacts(
  invariant: SynthesizedInvariant
): FormalPropertyArtifact[] {
  const name = safeIdentifier(invariant.id);
  const comments = assumptionComments(invariant);

  const halmos = [
    "// SPDX-License-Identifier: UNLICENSED",
    "pragma solidity ^0.8.20;",
    "",
    "// Generated by Risk Radar. Bind the target and observation hooks before proof.",
    "// Formula: " + invariant.formula,
    ...comments,
    "contract RiskRadar_" + name + "_Halmos {",
    "    address internal target = address(0); // RISK_RADAR_BIND_ME",
    "",
    "    function check_" + name + "() public {",
    "        // RISK_RADAR_BIND_ME: capture pre-state, invoke target transition,",
    "        // capture post-state and assert the synthesized property.",
    "        assert(target != address(0));",
    "    }",
    "}",
    ""
  ].join("\n");

  const certora = [
    "/*",
    " * Generated by Risk Radar.",
    " * Invariant: " + invariant.title,
    " * Formula: " + invariant.formula,
    " * Bind concrete getters/methods before proof.",
    " */",
    ...comments,
    "rule risk_radar_" + name + " {",
    "    // RISK_RADAR_BIND_ME",
    "    assert true;",
    "}",
    ""
  ].join("\n");

  const kontrol = [
    "// Risk Radar Kontrol property manifest",
    "// invariant: " + invariant.id,
    "// formula: " + invariant.formula,
    ...comments,
    "// RISK_RADAR_BIND_ME",
    ""
  ].join("\n");

  return [
    {
      invariantId: invariant.id,
      tool: "HALMOS",
      fileName:
        "RiskRadar_" + name + ".t.sol",
      content: halmos,
      requiresBinding: true
    },
    {
      invariantId: invariant.id,
      tool: "CERTORA",
      fileName:
        "RiskRadar_" + name + ".spec",
      content: certora,
      requiresBinding: true
    },
    {
      invariantId: invariant.id,
      tool: "KONTROL",
      fileName:
        "RiskRadar_" + name + ".kontrol.txt",
      content: kontrol,
      requiresBinding: true
    }
  ];
}

export async function writeFormalArtifacts(opts: {
  outputDir: string;
  invariants: SynthesizedInvariant[];
}) {
  const root = path.resolve(opts.outputDir);
  await fs.mkdir(root, { recursive: true });
  const written: string[] = [];
  for (const invariant of opts.invariants) {
    for (const artifact of generateFormalArtifacts(
      invariant
    )) {
      const filePath = path.join(
        root,
        artifact.fileName
      );
      if (path.dirname(filePath) !== root) {
        throw new Error(
          "Formal artifact path escaped output directory."
        );
      }
      await fs.writeFile(
        filePath,
        artifact.content,
        "utf8"
      );
      written.push(filePath);
    }
  }
  return written;
}

function severityFromOutput(
  output: string
): AnalysisSeverity {
  return /counterexample|fail|violat/i.test(output)
    ? "HIGH"
    : "INFO";
}

function disprovedFinding(
  job: FormalVerificationJob,
  output: string
) {
  const engine =
    job.tool === "HALMOS"
      ? "halmos"
      : job.tool === "KONTROL"
        ? "kontrol"
        : "certora";
  return finalizeFinding({
    id:
      "formal-" +
      job.tool.toLowerCase() +
      "-" +
      job.id,
    kind: "invariant_testing",
    engine,
    severity: severityFromOutput(output),
    confidence: "HIGH",
    evidenceStrength: "EXECUTED",
    evidenceClass:
      "FORMALLY_DISPROVED",
    title:
      job.tool +
      " produced a formal counterexample",
    description:
      output.slice(0, 2_000),
    proofVerdict:
      "DISPROVED_BY_COUNTEREXAMPLE",
    limitations: [
      "The counterexample is scoped to the exact property, harness, compiler and assumptions used by this formal job.",
      "Pinned-fork reproduction is still required before claiming deployed exploitability."
    ]
  });
}

export async function runFormalVerificationJob(
  job: FormalVerificationJob
): Promise<FormalVerificationResult> {
  const projectPath = path.resolve(
    job.projectPath
  );
  const propertyPath = path.resolve(
    job.propertyPath
  );
  if (
    propertyPath !== projectPath &&
    !propertyPath.startsWith(
      projectPath + path.sep
    )
  ) {
    throw new Error(
      "Formal property must remain inside the trusted project."
    );
  }

  const specification =
    await fs.readFile(propertyPath, "utf8");
  const configPath = job.configPath
    ? path.resolve(job.configPath)
    : undefined;
  if (
    configPath &&
    configPath !== projectPath &&
    !configPath.startsWith(
      projectPath + path.sep
    )
  ) {
    throw new Error(
      "Formal configuration must remain inside the trusted project."
    );
  }
  const configText = configPath
    ? await fs.readFile(configPath, "utf8")
    : "";
  const sanity = checkProofSanity({
    tool: job.tool,
    specification,
    configText
  });

  if (!sanity.passed) {
    return {
      jobId: job.id,
      tool: job.tool,
      state: "INCONCLUSIVE",
      proofVerdict: "INCONCLUSIVE",
      sanity,
      stdout: "",
      stderr: "",
      limitations: [
        "Formal execution was blocked because the specification failed proof-sanity checks."
      ]
    };
  }

  let executable = "";
  let args: string[] = [];
  if (job.tool === "HALMOS") {
    executable = "halmos";
    args = [];
  } else if (job.tool === "KONTROL") {
    executable = "kontrol";
    args = ["prove"];
  } else {
    executable = "certoraRun";
    if (!configPath) {
      return {
        jobId: job.id,
        tool: job.tool,
        state: "INCONCLUSIVE",
        proofVerdict: "INCONCLUSIVE",
        sanity,
        stdout: "",
        stderr: "",
        limitations: [
          "Certora requires an explicit project configuration file."
        ]
      };
    }
    args = [
      configPath,
      ...(job.allowRemote
        ? []
        : ["--compilation_steps_only"])
    ];
  }

  try {
    const result = await runBoundedProcess({
      executable,
      args,
      cwd: projectPath,
      timeoutMs: Math.max(
        10_000,
        Math.min(
          job.timeoutMs ?? 10 * 60_000,
          60 * 60_000
        )
      ),
      maxOutputBytes: 20_000_000
    });
    const combined =
      result.stdout + "\n" + result.stderr;
    const counterexample =
      /counterexample|falsified|\[FAIL\]|violat(?:ed|ion)/i.test(
        combined
      );

    if (counterexample) {
      return {
        jobId: job.id,
        tool: job.tool,
        state: "DISPROVED",
        proofVerdict:
          "DISPROVED_BY_COUNTEREXAMPLE",
        sanity,
        stdout: result.stdout,
        stderr: result.stderr,
        finding: disprovedFinding(
          job,
          combined
        ),
        limitations: [
          "Formal counterexample is scoped to this exact specification and assumptions."
        ]
      };
    }

    if (
      result.state === "complete" &&
      result.exitCode === 0
    ) {
      const proofExecuted =
        job.tool !== "CERTORA" ||
        Boolean(job.allowRemote);
      return {
        jobId: job.id,
        tool: job.tool,
        state: proofExecuted
          ? "PROVED_UNDER_SPEC"
          : "INCONCLUSIVE",
        proofVerdict: proofExecuted
          ? "PROVED_UNDER_SPEC"
          : "INCONCLUSIVE",
        sanity,
        stdout: result.stdout,
        stderr: result.stderr,
        limitations: proofExecuted
          ? [
              "Proof applies only to the exact specification, modeled environment and assumptions.",
              "A proof is not a protocol-wide claim of safety."
            ]
          : [
              "Certora compilation/sanity succeeded locally, but remote proof execution was deliberately not requested."
            ]
      };
    }

    return {
      jobId: job.id,
      tool: job.tool,
      state: "INCONCLUSIVE",
      proofVerdict: "INCONCLUSIVE",
      sanity,
      stdout: result.stdout,
      stderr: result.stderr,
      limitations: [
        "Formal tool did not produce a conclusive proof or counterexample."
      ]
    };
  } catch (error) {
    return {
      jobId: job.id,
      tool: job.tool,
      state: "UNAVAILABLE",
      proofVerdict: "INCONCLUSIVE",
      sanity,
      stdout: "",
      stderr:
        error instanceof Error
          ? error.message
          : String(error),
      limitations: [
        "Formal tool was unavailable or could not start."
      ]
    };
  }
}
